default_model = "DEEPSEEK"
prompt = "Analyze the following git diff and generate a concise and meaningful commit message summarizing the changes.\nThe commit message should follow best practices, including a short title and an optional detailed description if necessary.\ngit diff:\n{}\nRequirements:\n  Title: 50 characters or less, summarizing the change.\n  Optional Description: If the change requires context, provide a brief explanation in the body.\n"

[api_keys]
gemini_api_key = "api_key"
deepseek_api_key = "api_key"
